#!/usr/bin/env python3
"""Extract registries/snippets from the process doc; stage the runtime files.

Block classification: a fenced ```bash or ```python block is classified by the
nearest preceding HTML comment of the form <!-- lint: snippet --> (the only
marker the document still carries -- the cookbook and publisher are authored
directly under runtime/), searching upward past blank lines only. Anything
else is 'unmarked'. The `cookbook` and `publisher` subcommands are verbatim
copies of runtime/cookbook.sh and runtime/publish-status into $BUILD.
"""
import os
import pathlib
import re
import sys

REPO_TOP = pathlib.Path(__file__).resolve().parents[2]
DOC = pathlib.Path(os.environ.get("PROCESS_DOC", REPO_TOP / "develop-it-prompt.md"))
BUILD = pathlib.Path(os.environ.get("BUILD", REPO_TOP / "tests" / ".build"))

MARKER = re.compile(r"^[ \t]*<!--\s*lint:\s*(cookbook|snippet|publisher)\s*-->\s*$")
FENCE_OPEN = re.compile(r"^([ \t]*)```(bash|python)[ \t]*$")
FENCE_CLOSE = re.compile(r"^([ \t]*)```[ \t]*$")

# Preamble for snippet blocks: they legitimately reference orchestration
# variables they do not define, so declare them to keep `bash -n` and
# shellcheck focused on real syntax errors rather than SC2154.
SNIPPET_PREAMBLE = """#!/usr/bin/env bash
# AUTO-GENERATED by tests/lib/extract.py -- do not edit.
set -uo pipefail
PROCESS_PATH=/dev/null; REPO_ROOT=/tmp; PROCESS_REPO_ROOT=/tmp
FEATURE_FOLDER=/tmp/ff; SPEC_PATH=/dev/null; PLAN_PATH=/dev/null
FINDINGS_PATHS=""; ITERATION=01; ROUND=01; TEST_REPORT_PATH=/dev/null
IMPLEMENTATION_BASE_SHA=deadbeef; IMPLEMENTATION_SUMMARY_PATH=/dev/null
DEBUGGER_STATUS_PATH=/dev/null; PYTHON_BIN=python3; GREP_BIN=/usr/bin/grep
CLAUDE_MODEL=claude-sonnet-5; CODEX_MODEL=gpt-5.6-sol; STATUS=/dev/null
codex_available=false; role=noop; out_json=/dev/null; wall_ms=0
"""


def _dedent(line, indent):
    """Strip exactly `indent` from `line`, tolerating blank lines that carry no
    trailing whitespace of their own."""
    if not indent:
        return line
    if line[:len(indent)] == indent:
        return line[len(indent):]
    if line.strip() == "":
        return ""
    return line


def blocks():
    """Yield (kind, language, start_line, [body_lines]) for every fenced bash
    or python block.

    A fence may be indented (e.g. nested inside a numbered list item). The
    indent of the OPENING fence is captured and stripped from every body line,
    and the block only closes on a fence at that SAME indent -- a fence at a
    different indent is body content, not the terminator.
    """
    lines = DOC.read_text().splitlines()
    i = 0
    while i < len(lines):
        m_open = FENCE_OPEN.match(lines[i])
        if m_open:
            indent, language = m_open.group(1), m_open.group(2)
            # Walk upward past blank lines looking for a lint marker.
            kind = "unmarked"
            j = i - 1
            while j >= 0 and lines[j].strip() == "":
                j -= 1
            if j >= 0:
                m = MARKER.match(lines[j])
                if m:
                    kind = m.group(1)
            body, k = [], i + 1
            while k < len(lines):
                m_close = FENCE_CLOSE.match(lines[k])
                if m_close and m_close.group(1) == indent:
                    break
                body.append(lines[k])
                k += 1
            body = [_dedent(b, indent) for b in body]
            yield kind, language, i + 1, body
            i = k + 1
        else:
            i += 1


def cmd_cookbook():
    """Stage the directly-authored cookbook into $BUILD for the checks.

    The cookbook is no longer extracted from fenced document blocks -- it is
    authored at runtime/cookbook.sh (the document keeps only a function
    index) -- so this is a verbatim copy, kept as a subcommand so every
    existing $BUILD/cookbook.sh consumer stays pointed at one place.
    """
    BUILD.mkdir(parents=True, exist_ok=True)
    src = REPO_TOP / "runtime" / "cookbook.sh"
    if not src.is_file():
        sys.stderr.write(f"extract.py: missing {src}\n")
        return 1
    (BUILD / "cookbook.sh").write_text(src.read_text())
    return 0


def cmd_publisher() -> int:
    """Stage the directly-authored publisher (runtime/publish-status) into
    $BUILD -- a verbatim copy, same rationale as cmd_cookbook."""
    BUILD.mkdir(parents=True, exist_ok=True)
    src = REPO_TOP / "runtime" / "publish-status"
    if not src.is_file():
        raise SystemExit(f"extract.py: missing {src}")
    source = src.read_text()
    (BUILD / "publish-status").write_text(source)
    sys.stdout.write(source)
    return 0


def cmd_snippets():
    d = BUILD / "snippets"
    d.mkdir(parents=True, exist_ok=True)
    for f in d.glob("*.sh"):
        f.unlink()
    for kind, language, line, body in blocks():
        if kind != "snippet" or language != "bash":
            continue
        (d / f"{line:04d}.sh").write_text(SNIPPET_PREAMBLE + "\n".join(body) + "\n")
    return 0


def cmd_unmarked():
    rc = 0
    for kind, language, line, _ in blocks():
        if kind == "unmarked":
            print(line)
            rc = 1
    return rc


ROLE_COLUMNS = (
    "role", "vendor", "model", "effort", "timeout_minutes", "mutates",
    "long_running", "may_spawn_children", "required_inputs", "optional_inputs",
    "status_template", "outputs", "verdicts", "required_status_fields",
    "checkpoint_kind", "phases",
)

TABLE_SPECS = {
    "policies": ("Process Policy Registry", ("policy", "value", "meaning")),
    "events": ("Event Contract Registry", ("event_type", "required_fields", "proposition_required")),
    "recovery": (
        "Recovery Matrix",
        ("matrix_id", "classification", "mutation_state", "action"),
    ),
    "roles": ("Role Contract Registry", ROLE_COLUMNS),
}


def normalized_header(cell: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", cell.strip().lower()).strip("_")


def section_after_heading(text: str, heading: str) -> str:
    pattern = re.compile(rf"^(?P<level>#+)\s+{re.escape(heading)}\s*$", re.MULTILINE)
    match = pattern.search(text)
    if match is None:
        raise SystemExit(f"missing heading: {heading}")
    level = len(match.group("level"))
    tail = text[match.end():]
    next_heading = re.search(rf"^#{{1,{level}}}\s+", tail, re.MULTILINE)
    return tail if next_heading is None else tail[:next_heading.start()]


def markdown_rows(section: str) -> list[list[str]]:
    rows = []
    for raw in section.splitlines():
        if not raw.startswith("|"):
            if rows:
                break
            continue
        rows.append([cell.strip().strip("`") for cell in raw.strip().strip("|").split("|")])
    if len(rows) < 3:
        raise SystemExit("table has no data rows")
    if any(set(cell) - set("-: ") for cell in rows[1]):
        raise SystemExit("table separator is malformed")
    return rows


def named_markdown_table(text: str, heading: str, columns: tuple[str, ...]) -> list[list[str]]:
    section = section_after_heading(text, heading)
    rows = markdown_rows(section)
    actual = tuple(normalized_header(cell) for cell in rows[0])
    if actual != columns:
        raise SystemExit(f"{heading}: expected columns {columns}, got {actual}")
    for row in rows[2:]:
        if len(row) != len(columns) or any("\t" in cell or "\n" in cell for cell in row):
            raise SystemExit(f"{heading}: invalid row {row}")
    return [list(columns), *rows[2:]]


def cmd_named_table(name):
    heading, columns = TABLE_SPECS[name]
    BUILD.mkdir(parents=True, exist_ok=True)
    rows = named_markdown_table(DOC.read_text(), heading, columns)
    header, data = rows[0], rows[1:]
    seen = set()
    for row in data:
        key = row[0]
        if key in seen:
            raise SystemExit(f"{heading}: duplicate key {key}")
        seen.add(key)
    lines = ["\t".join(header)] + ["\t".join(row) for row in data]
    text = "\n".join(lines) + "\n"
    (BUILD / f"{name}.tsv").write_text(text)
    sys.stdout.write(text)
    return 0


def cmd_policies():
    return cmd_named_table("policies")


def cmd_events():
    return cmd_named_table("events")


def cmd_recovery():
    return cmd_named_table("recovery")


def _long_role_headroom_threshold_minutes(doc_text: str) -> int:
    """The `long_role_headroom_threshold_minutes` policy value, read straight
    from the Process Policy Registry table -- never hardcoded here, so the
    long_running derivation rule below cannot silently drift from Task 1's
    policy table if that threshold is ever revised."""
    heading, columns = TABLE_SPECS["policies"]
    rows = named_markdown_table(doc_text, heading, columns)
    for row in rows[1:]:
        if row[0] == "long_role_headroom_threshold_minutes":
            return int(row[1])
    raise SystemExit("long_role_headroom_threshold_minutes missing from Process Policy Registry")


def cmd_roles():
    """Emit the full 16-column role-contract registry as TSV.

    Unlike policies/events/recovery, this does NOT use cmd_named_table: role
    uniqueness is deliberately NOT enforced here. `role_contract_field` (the
    cookbook awk lookup) is the sole enforcement point for an unknown-or-
    duplicate role (exit 43) -- pre-deduping here would make that runtime path
    unreachable and untestable. named_markdown_table is still reused for the
    header-shape/heading location logic, per extractor convention.

    Also rejects `long_running` DRIFT: the column is a materialized (not
    hand-picked) value -- spec 6.1 derives it "from timeout/child behavior" --
    so a row whose declared long_running disagrees with that derivation is a
    process-definition bug, caught here rather than silently trusted.
    """
    BUILD.mkdir(parents=True, exist_ok=True)
    doc_text = DOC.read_text()
    heading, columns = TABLE_SPECS["roles"]
    rows = named_markdown_table(doc_text, heading, columns)
    header, data = rows[0], rows[1:]
    if not data:
        sys.stderr.write("extract.py: role table has no rows\n")
        return 1
    norm = lambda v: "" if v in {"—", "-", "n/a", ""} else v  # noqa: E731

    threshold = _long_role_headroom_threshold_minutes(doc_text)
    idx = {name: i for i, name in enumerate(columns)}
    lines = ["\t".join(header)]
    for row in data:
        cells = [norm(cell) for cell in row]
        role = cells[idx["role"]]
        timeout_raw = cells[idx["timeout_minutes"]]
        declared_lr = cells[idx["long_running"]]
        may_spawn = cells[idx["may_spawn_children"]]
        phases = cells[idx["phases"]]
        try:
            timeout = int(timeout_raw)
        except ValueError:
            raise SystemExit(f"{heading}: {role} has a non-integer timeout_minutes: {timeout_raw!r}")
        # "Derived from timeout/child behavior" (spec 6.1): a long timeout, a
        # child-only contract, or a role that spawns children all qualify.
        expected_lr = "yes" if (timeout >= threshold or phases == "child" or may_spawn == "yes") else "no"
        if declared_lr != expected_lr:
            raise SystemExit(
                f"{heading}: {role} declares long_running={declared_lr!r} but "
                f"timeout_minutes={timeout}/phases={phases!r}/may_spawn_children={may_spawn!r} "
                f"(threshold={threshold}) derives long_running={expected_lr!r}"
            )
        lines.append("\t".join(cells))
    text_out = "\n".join(lines) + "\n"
    (BUILD / "roles.tsv").write_text(text_out)
    sys.stdout.write(text_out)
    return 0


CMDS = {"cookbook": cmd_cookbook, "snippets": cmd_snippets,
        "roles": cmd_roles, "unmarked": cmd_unmarked,
        "policies": cmd_policies, "events": cmd_events, "recovery": cmd_recovery,
        "publisher": cmd_publisher}

if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in CMDS:
        sys.stderr.write(f"usage: extract.py {{{'|'.join(CMDS)}}}\n")
        sys.exit(2)
    sys.exit(CMDS[sys.argv[1]]())
