#!/usr/bin/env python3
"""Extract lint-classified shell blocks and the role table from the process doc.

Block classification: a fenced ```bash block is classified by the nearest
preceding HTML comment of the form <!-- lint: cookbook --> or <!-- lint: snippet -->,
searching upward past blank lines only. Anything else is 'unmarked'.
"""
import os
import pathlib
import re
import sys

REPO_TOP = pathlib.Path(__file__).resolve().parents[2]
DOC = pathlib.Path(os.environ.get("PROCESS_DOC", REPO_TOP / "develop-it-prompt.md"))
BUILD = pathlib.Path(os.environ.get("BUILD", REPO_TOP / "tests" / ".build"))

MARKER = re.compile(r"^[ \t]*<!--\s*lint:\s*(cookbook|snippet)\s*-->\s*$")
FENCE_OPEN = re.compile(r"^([ \t]*)```bash[ \t]*$")
FENCE_CLOSE = re.compile(r"^([ \t]*)```[ \t]*$")

# Preamble for snippet blocks: they legitimately reference orchestration
# variables they do not define, so declare them to keep `bash -n` and
# shellcheck focused on real syntax errors rather than SC2154.
SNIPPET_PREAMBLE = """#!/usr/bin/env bash
# AUTO-GENERATED by tests/lib/extract.py -- do not edit.
set -uo pipefail
PROCESS_PATH=/dev/null; REPO_ROOT=/tmp; PROCESS_REPO_ROOT=/tmp
FEATURE_FOLDER=/tmp/ff; SPEC_PATH=/dev/null; PLAN_PATH=/dev/null
FINDINGS_PATHS=""; ITERATION=01; ROUND=01; TEST_REPORT_PATH=/dev/null
IMPLEMENTATION_BASE_SHA=deadbeef; IMPLEMENTATION_SUMMARY_PATH=/dev/null
DEBUGGER_STATUS_PATH=/dev/null; PYTHON_BIN=python3; GREP_BIN=/usr/bin/grep
CLAUDE_MODEL=claude-sonnet-5; CODEX_MODEL=gpt-5.6-sol; STATUS=/dev/null
codex_available=false; role=noop; out_json=/dev/null; wall_ms=0
"""


def _dedent(line, indent):
    """Strip exactly `indent` from `line`, tolerating blank lines that carry no
    trailing whitespace of their own."""
    if not indent:
        return line
    if line[:len(indent)] == indent:
        return line[len(indent):]
    if line.strip() == "":
        return ""
    return line


def blocks():
    """Yield (kind, start_line, [body_lines]) for every fenced bash block.

    A fence may be indented (e.g. nested inside a numbered list item). The
    indent of the OPENING fence is captured and stripped from every body line,
    and the block only closes on a fence at that SAME indent -- a fence at a
    different indent is body content, not the terminator.
    """
    lines = DOC.read_text().splitlines()
    i = 0
    while i < len(lines):
        m_open = FENCE_OPEN.match(lines[i])
        if m_open:
            indent = m_open.group(1)
            # Walk upward past blank lines looking for a lint marker.
            kind = "unmarked"
            j = i - 1
            while j >= 0 and lines[j].strip() == "":
                j -= 1
            if j >= 0:
                m = MARKER.match(lines[j])
                if m:
                    kind = m.group(1)
            body, k = [], i + 1
            while k < len(lines):
                m_close = FENCE_CLOSE.match(lines[k])
                if m_close and m_close.group(1) == indent:
                    break
                body.append(lines[k])
                k += 1
            body = [_dedent(b, indent) for b in body]
            yield kind, i + 1, body
            i = k + 1
        else:
            i += 1


def cmd_cookbook():
    BUILD.mkdir(parents=True, exist_ok=True)
    out = ["#!/usr/bin/env bash",
           "# AUTO-GENERATED by tests/lib/extract.py -- do not edit.",
           "# shellcheck shell=bash"]
    found = 0
    for kind, line, body in blocks():
        if kind != "cookbook":
            continue
        found += 1
        out.append(f"# --- from {DOC.name}:{line} ---")
        out.extend(body)
    if not found:
        sys.stderr.write("extract.py: no 'lint: cookbook' blocks found\n")
        return 1
    (BUILD / "cookbook.sh").write_text("\n".join(out) + "\n")
    return 0


def cmd_snippets():
    d = BUILD / "snippets"
    d.mkdir(parents=True, exist_ok=True)
    for f in d.glob("*.sh"):
        f.unlink()
    for kind, line, body in blocks():
        if kind != "snippet":
            continue
        (d / f"{line:04d}.sh").write_text(SNIPPET_PREAMBLE + "\n".join(body) + "\n")
    return 0


def cmd_unmarked():
    rc = 0
    for kind, line, _ in blocks():
        if kind == "unmarked":
            print(line)
            rc = 1
    return rc


def cmd_roles():
    """Emit the role table as TSV: role, vendor, model, effort, timeout_min.

    The table is located by its header row, which must contain all five
    column names. Cells are stripped of backticks and surrounding space.
    An em-dash or empty cell becomes the empty string.
    """
    BUILD.mkdir(parents=True, exist_ok=True)
    rows, in_table = [], False
    for raw in DOC.read_text().splitlines():
        if not raw.startswith("|"):
            if in_table:
                break
            continue
        cells = [c.strip().strip("`").strip() for c in raw.strip().strip("|").split("|")]
        low = [c.lower() for c in cells]
        if not in_table:
            if {"role", "vendor", "model", "effort", "timeout"} <= set(
                w for c in low for w in c.split()
            ):
                in_table = True
            continue
        if set("".join(cells)) <= set("-: "):
            continue  # separator row
        if len(cells) < 5:
            continue
        role, vendor, model, effort, timeout = cells[:5]
        norm = lambda v: "" if v in {"—", "-", "n/a", ""} else v  # noqa: E731
        rows.append("\t".join([role, norm(vendor), norm(model),
                               norm(effort), norm(timeout)]))
    if not rows:
        sys.stderr.write("extract.py: role table not found\n")
        return 1
    (BUILD / "roles.tsv").write_text("\n".join(rows) + "\n")
    return 0


CMDS = {"cookbook": cmd_cookbook, "snippets": cmd_snippets,
        "roles": cmd_roles, "unmarked": cmd_unmarked}

if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in CMDS:
        sys.stderr.write(f"usage: extract.py {{{'|'.join(CMDS)}}}\n")
        sys.exit(2)
    sys.exit(CMDS[sys.argv[1]]())
